name: Ubuntu Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    #compiler: [ latest, gcc-latest, gcc-9, gcc-10, g++-11, clang, clang-10, clang-11, clang++-12 ]
    compiler: g++-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    #- name: Setup openGL
    #  uses: openrndr/setup-opengl@v1.1

    #- name: xvfb-Run 
    #  run: xvfb-run glxinfo
        
    - name: Installing asound gsound, gtk-3, doxygen
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev libgsound-dev libgtk-3-dev doxygen

    - name: Build
      # Build your program with the given configuration
      run: scripts/github/build_xtd_and_launch_unit_tests_on_linux.sh
      
